# Generated by Django 5.2.8 on 2025-11-26 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Đường dẫn')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('featured_image', models.CharField(blank=True, max_length=200, verbose_name='Ảnh bìa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng')),
                ('is_published', models.BooleanField(default=True, verbose_name='Đã xuất bản')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tin nổi bật')),
            ],
            options={
                'verbose_name': 'Tin công ty',
                'verbose_name_plural': 'Tin công ty',
                'ordering': ['-created_at'],
            },
        ),
    ]
