# Generated by Django 5.2.7 on 2025-11-26 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_featured_image_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('summary', models.TextField(blank=True, verbose_name='Tóm tắt')),
                ('source', models.CharField(choices=[('customs', 'Tổng cục Hải quan'), ('logistics', 'Cục Logistics Việt Nam')], max_length=20, verbose_name='Nguồn')),
                ('source_url', models.URLField(verbose_name='Liên kết gốc')),
                ('published_date', models.DateTimeField(verbose_name='Ngày xuất bản')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày lấy tin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Tin chuyên ngành',
                'verbose_name_plural': 'Tin chuyên ngành',
                'ordering': ['-published_date'],
                'unique_together': {('source_url', 'source')},
            },
        ),
    ]
