# Generated by Django 5.2.8 on 2025-12-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_externalnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung (English)'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung (Chinese)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề (English)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_zh_hans',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề (Chinese)'),
        ),
    ]
